identifier: pl.nanoray.glint.bungie
pluginClassName: pl.nanoray.glint.bungie.BungiePlugin
dependencies:
  - {identifier: pl.nanoray.glint.http}
  - {identifier: pl.nanoray.glint.http.oauth}
  - {identifier: pl.nanoray.glint.store}
  - {identifier: pl.nanoray.glint.slashcommand}