identifier: pl.nanoray.glint.messagecommand
pluginClassName: pl.nanoray.glint.messagecommand.MessageCommandPlugin
dependencies:
- {identifier: pl.nanoray.glint.command}
- {identifier: pl.nanoray.glint.owner}
- {identifier: pl.nanoray.glint.store}